const meanZhMap = {
  "ability or size": "能力或容量",
  "ability to read and write": "讀寫能力",
  "able to be seen": "看得見的",
  "able to compete well": "具競爭力的",
  "able to continue over time": "可持續的",
  "able to recover": "有復原力的",
  "about but not exactly": "大約但不精確",
  "accept officially": "正式批准",
  "accept without proof": "未經證明便假定",
  "act of joining": "加入行為",
  "activity done for enjoyment": "休閒活動",
  "adjust to new conditions": "適應新情況",
  "after that": "之後",
  "agreement": "協議",
  "all employees": "全體員工",
  "allowed by law": "合法的",
  "almost": "幾乎",
  "almost not": "幾乎不",
  "always acting the same way": "一致的",
  "amount or size": "數量或體積",
  "amount produced": "產出量",
  "amount spent": "支出金額",
  "area": "區域",
  "arrange": "安排",
  "arrange into groups": "分類編組",
  "arranged in a neat way": "整齊有序的",
  "arranged meeting time": "預約時間",
  "arrangement of parts": "結構",
  "arriving after expected time": "遲到的",
  "as a result": "因此",
  "ask for payment": "收費",
  "ask someone to come": "邀請",
  "aspect": "面向",
  "assess": "評估",
  "assign responsibility": "指派責任",
  "at first": "起初",
  "at fixed times": "定期地",
  "at last": "終於",
  "at low speed": "慢慢地",
  "aware": "有意識的",
  "bag carried on the back": "背包",
  "bags for travel": "行李",
  "based on observation": "基於觀察的",
  "based on reason": "理性的",
  "basic and important": "基礎且重要的",
  "basic structure": "架構",
  "basic support": "基礎支撐",
  "basic truth": "基本原理",
  "become larger": "擴大",
  "become less": "減少",
  "before expected time": "提早地",
  "belief taken as true": "假設",
  "bend over on itself": "摺疊",
  "billing document": "發票",
  "book for notes": "筆記本",
  "book in advance": "預訂",
  "booking": "預約",
  "box for receiving letters": "信箱",
  "bring back to earlier condition": "恢復原狀",
  "bring goods": "運送貨物",
  "bring goods into a country": "進口",
  "bring to a place": "送達",
  "building or service": "設施",
  "business exchange": "交易",
  "business relationship": "合作關係",
  "buy": "購買",
  "buy things": "購物",
  "buyer of products": "消費者",
  "car for hire": "計程車",
  "careful in choosing": "精挑細選的",
  "careful study": "分析",
  "carry out": "執行",
  "casual sports shoes": "運動休閒鞋",
  "certain to happen": "不可避免的",
  "change": "變化",
  "change completely": "徹底改變",
  "change for improvement": "修訂",
  "change into another form": "轉換",
  "check carefully": "仔細檢查",
  "check that something is true": "驗證",
  "clean with suction": "用吸塵器清潔",
  "clean with water": "清洗",
  "cleaning agent": "清潔劑",
  "clear and detailed": "生動清晰的",
  "clear difference": "對比",
  "clearly stated": "明確的",
  "close but not exact": "近似的",
  "closely connected": "相關的",
  "cloth for drying": "毛巾",
  "clothes to be washed": "待洗衣物",
  "collect into one work": "彙編",
  "combine": "合併",
  "combine into a whole": "綜合",
  "come into view": "出現",
  "coming from outside": "外部的",
  "communicate": "傳達",
  "communicate with": "聯絡",
  "company combination": "合併",
  "company division": "部門",
  "company hiring workers": "雇主",
  "company providing goods": "供應商",
  "compared with something else": "相對地",
  "complete and detailed": "全面詳盡的",
  "complete officially": "正式完成",
  "condition surrounding an event": "情況",
  "confirm": "確認",
  "confirm officially": "正式證明",
  "containing as much as possible": "滿的",
  "containing nothing": "空的",
  "continue toward a goal": "追求",
  "control strongly": "主導",
  "convince": "說服",
  "cooking device": "爐具",
  "cooking instructions": "食譜",
  "correct and exact": "準確的",
  "cost": "成本",
  "cost of a ride": "車資",
  "coworker": "同事",
  "customer": "顧客",
  "dealing with ideas not concrete things": "抽象的",
  "decide after thinking": "下結論",
  "deep understanding": "洞見",
  "delay": "延後",
  "deliver to many places": "配送",
  "dependable": "可靠的",
  "device for adding power": "充電器",
  "device for controlling electronics": "遙控器",
  "device giving light": "燈",
  "device storing power": "電池",
  "device with keys for typing": "鍵盤",
  "difference in form": "變化",
  "different choice": "替代方案",
  "difficult choice": "兩難",
  "discount ticket": "優惠券",
  "discover": "發現",
  "discuss terms": "協商",
  "discussion to reach agreement": "談判",
  "distribute resources": "分配資源",
  "do physical activity": "運動",
  "doctor for teeth": "牙醫",
  "doctor order": "處方",
  "done by a group": "集體的",
  "draw a conclusion": "推論",
  "drawing of an area": "地圖",
  "drink": "飲料",
  "drug for treating illness": "藥物",
  "due date": "截止日",
  "easy to adjust": "靈活的",
  "easy to use": "方便的",
  "employ": "雇用",
  "employee payment list": "薪資名冊",
  "employees": "員工",
  "enough": "足夠的",
  "equipment worn on ears to hear sound": "耳機",
  "every three months": "每季的",
  "every week": "每週",
  "every year": "每年",
  "exact": "精確的",
  "examine carefully": "仔細檢視",
  "experience": "經歷",
  "explain meaning": "解釋意思",
  "explanation of meaning": "詮釋",
  "extend the body or material": "伸展",
  "extra payment": "獎金",
  "extremely cold": "極冷的",
  "extremely important": "關鍵的",
  "far away": "偏遠的",
  "field of study": "學科",
  "figurative comparison": "隱喻",
  "final judgment": "結論",
  "final or most important": "最終的",
  "financial gain": "利潤",
  "financial protection": "保險",
  "financial support": "補助",
  "firm and easy to break": "酥脆的",
  "first meal of the day": "早餐",
  "fix": "修理",
  "fixed pay": "薪水",
  "flat storage board": "架子",
  "following common practice": "傳統的",
  "following official style": "正式的",
  "following rules": "合規",
  "food component": "食材",
  "food supplies": "雜貨",
  "formal meeting": "會議",
  "formal plan": "提案",
  "from nearby area": "本地的",
  "full of people": "擁擠的",
  "gather over time": "累積",
  "general direction of change": "趨勢",
  "general idea": "概念",
  "get": "取得",
  "get from a source": "源自",
  "give approval": "核准",
  "give back or go back": "歸還",
  "give support": "鼓勵",
  "giving useful help": "有幫助的",
  "go to see": "拜訪",
  "goal": "目標",
  "good reason": "正當理由",
  "goods sent": "貨運",
  "group of similar things": "類別",
  "grow larger": "擴張",
  "hand in": "提交",
  "handle systematically": "處理",
  "happen together": "同時發生",
  "happening at once": "立即的",
  "happening every day": "每日的",
  "happening often": "頻繁的",
  "happening slowly": "逐漸的",
  "harmful or not positive": "負面的",
  "have clothes on the body": "穿著",
  "having a lot of room": "寬敞的",
  "having a lot to do": "忙碌的",
  "having ability": "有能力的",
  "having many parts": "複雜的",
  "head support for sleeping": "枕頭",
  "health and happiness": "福祉",
  "hire": "雇用",
  "household machine": "家電",
  "idea": "想法",
  "imitate conditions": "模擬",
  "importance": "重要性",
  "important element": "因素",
  "important for long-term plans": "策略性的",
  "important problem": "議題",
  "improve": "改善",
  "in a firm exact way": "嚴格地",
  "in a productive way": "有效率地",
  "in a safe way": "安全地",
  "in a suitable way": "適當地",
  "in a transparent way": "公開地",
  "in advance": "事先",
  "in an important way": "顯著地",
  "in an official way": "正式地",
  "in another country": "在國外",
  "in or toward the city center": "在市中心",
  "in terms of history": "就歷史而言",
  "in the end": "最後",
  "in the open air": "在戶外",
  "in the same way over time": "持續一致地",
  "in the usual way": "通常地",
  "include as part": "納入",
  "income": "收入",
  "inform officially": "正式通知",
  "informal": "休閒的",
  "informational booklet": "宣傳手冊",
  "inside": "內部的",
  "inside a building": "在室內",
  "interested party": "利害關係人",
  "international travel document": "護照",
  "introducing new ideas": "創新的",
  "invited visitor": "客人",
  "invoice": "帳單",
  "job summary document": "履歷",
  "keep": "保留",
  "keep from harm": "保存",
  "keep in good condition": "維護",
  "kind and pleasant": "友善的",
  "lasting a short time": "暫時的",
  "late": "逾期的",
  "later": "之後",
  "leave a job": "辭職",
  "leave a vehicle temporarily": "停車",
  "leave out": "排除",
  "let others use or know": "分享",
  "licensed business branch": "加盟店",
  "likelihood": "機率",
  "limit": "限制",
  "limitation": "限制",
  "liquid for washing hair": "洗髮精",
  "list of food choices": "菜單",
  "local office": "分公司",
  "logically connected": "連貫的",
  "long-lasting": "耐用的",
  "long-term plan": "策略",
  "low in price": "便宜的",
  "made by people": "人工的",
  "main evening meal": "晚餐",
  "main office": "總部",
  "main subject": "主題",
  "mainly": "主要地",
  "make clear": "釐清",
  "make clear with examples": "說明",
  "make current": "更新",
  "make easier": "促進",
  "make free from dirt": "清潔",
  "make known": "揭露",
  "make less severe": "減輕",
  "make people obey": "強制執行",
  "make products": "製造",
  "make ready": "準備",
  "make shiny and smooth": "擦亮",
  "make stronger": "加強",
  "make up for": "補償",
  "make valid again": "續約",
  "make warm or hot": "加熱",
  "making a lot of sound": "吵雜的",
  "making little sound": "安靜的",
  "making money": "獲利的",
  "making no sound": "無聲的",
  "marked place to cross a road": "行人穿越道",
  "marketing activity": "促銷活動",
  "medical cream": "藥膏",
  "meeting plan": "議程",
  "method": "方法",
  "midday meal": "午餐",
  "model of real conditions": "模擬",
  "money returned": "退款",
  "morally right": "合乎倫理的",
  "more than enough": "充足的",
  "move from one place to another": "移轉",
  "movement of goods": "物流",
  "movement of vehicles": "交通流量",
  "moving lift": "電梯",
  "neat and in order": "整潔的",
  "new idea or method": "創新",
  "new in style or method": "現代的",
  "next to": "相鄰的",
  "not changing": "固定的",
  "not changing much": "穩定的",
  "not clean": "髒的",
  "not completely": "部分地",
  "not dangerous": "安全的",
  "not far away": "附近地",
  "not fast": "緩慢的",
  "not flexible": "僵硬的",
  "not obvious": "微妙的",
  "not often": "很少",
  "not permanent": "暫時的",
  "not sleeping": "醒著的",
  "not special": "普通的",
  "not taking sides": "中立的",
  "not too expensive": "價格實惠的",
  "not willing to work": "懶惰的",
  "notice or understand": "察覺",
  "observable event": "現象",
  "official and proper": "正式的",
  "official document": "證明文件",
  "official permit": "執照",
  "official review": "稽核",
  "official rule": "政策",
  "official written records": "文件資料",
  "often": "經常",
  "old in age": "年長的",
  "on purpose": "故意地",
  "on the previous day": "昨天",
  "one of a kind": "獨特的",
  "only": "僅僅",
  "open position": "職缺",
  "order medicine": "開立處方",
  "ordered series": "序列",
  "organize together": "協調",
  "organized data collection": "資料庫",
  "organized promotion effort": "宣傳活動",
  "outdoor platform on a building": "陽台",
  "over a large area": "廣泛地",
  "oversee work": "監督",
  "owner of company shares": "股東",
  "part in relation to whole": "比例",
  "part of a whole": "組成部分",
  "part of society or economy": "部門",
  "particular form": "版本",
  "pass for travel or entry": "票券",
  "passage inside a building": "走廊",
  "paste for brushing teeth": "牙膏",
  "path from one place to another": "路線",
  "pay back expenses": "報銷",
  "payment counter": "結帳櫃台",
  "peaceful": "平靜的",
  "person applying": "申請者",
  "person living nearby": "鄰居",
  "person receiving guests": "主人",
  "person serving food": "服務生",
  "person who travels to work": "通勤者",
  "place where vehicles stop": "車站",
  "pleasant to use or wear": "舒適的",
  "point of view": "觀點",
  "polite or related to citizens": "公民的或有禮的",
  "possible customer or future chance": "潛在客戶或機會",
  "pour water on": "澆水",
  "practical": "可行的",
  "prediction": "預測",
  "prepare food with heat": "烹煮",
  "prepared": "準備好的",
  "present": "禮物",
  "price reduction": "折扣",
  "private": "機密的",
  "produce": "產生",
  "producing a lot": "高產的",
  "producing the intended result": "有效的",
  "productive": "有生產力的",
  "professional adviser": "顧問",
  "promote publicly": "宣傳",
  "proof": "證據",
  "proof of purchase": "購買證明",
  "property owner": "房東",
  "proposed explanation": "假說",
  "protective head covering": "安全帽",
  "public disagreement": "爭議",
  "public promotion message": "廣告",
  "put a new one in place of an old one": "更換",
  "put in money": "投資",
  "put things into a bag": "打包",
  "put together": "組裝",
  "questionnaire study": "問卷調查",
  "range": "範圍",
  "ranked order": "階層",
  "rate of sales or staff change": "周轉率",
  "react": "回應",
  "ready for use": "可使用的",
  "reason for action": "動機",
  "reasonable in thought": "合理的",
  "reasoning behind something": "理據",
  "recent and not old": "新鮮的",
  "recently": "最近",
  "recommended rule": "指引",
  "record officially": "登記",
  "reduce as much as possible": "盡量減少",
  "reflective surface": "鏡子",
  "registered brand sign": "商標",
  "regular paid service": "訂閱服務",
  "related to a company": "企業的",
  "related to living things": "生物的",
  "related to money": "財務的",
  "relating to one area": "地區的",
  "remove from a bag or box": "拆包",
  "remove moisture": "弄乾",
  "repair and improve": "整修",
  "repair promise": "保固",
  "required": "強制的",
  "required amount": "配額",
  "reserve in advance": "預留",
  "rest and become calm": "放鬆",
  "result": "結果",
  "road crossing": "路口",
  "room for cooking": "廚房",
  "rough calculation": "估算",
  "roughly judge value": "估計",
  "run a business or machine": "操作",
  "sales payment": "佣金",
  "save for future use": "節省",
  "say in advance": "預測",
  "secure with a key": "上鎖",
  "seek advice": "諮詢",
  "seeming contradiction": "悖論",
  "seemingly reasonable": "貌似合理的",
  "selected list of songs": "播放清單",
  "seller": "賣方",
  "separate section": "部門",
  "serious disagreement": "衝突",
  "serious or sharp": "嚴重的或尖銳的",
  "set of investments": "投資組合",
  "set up equipment": "安裝",
  "shared by two sides": "相互的",
  "short in time or words": "簡短的",
  "short main account": "摘要",
  "short official note": "備忘錄",
  "short outer coat": "夾克",
  "show": "顯示",
  "show a difference": "區分",
  "show or think carefully": "反映或反思",
  "show to be right": "證明正當",
  "showing good manners": "有禮貌的",
  "showing skill and care": "專業的",
  "showing variety": "多元的",
  "sign of illness": "症狀",
  "similar and developing together": "平行的",
  "single-seller control": "壟斷",
  "sliding storage box": "抽屜",
  "slightly hot in a pleasant way": "溫暖的",
  "slowly over time": "逐漸地",
  "small amount of food": "點心",
  "small but complete": "緊湊的",
  "small case for money and cards": "皮夾",
  "small medical center": "診所",
  "small or limited": "邊際的",
  "small storage space": "衣櫥",
  "soft bed support": "床墊",
  "soft coverings for feet": "襪子",
  "soft indoor shoes": "拖鞋",
  "soft support pad": "靠墊",
  "solve": "解決",
  "something treated as more important": "優先事項",
  "space for leaving a vehicle": "停車位",
  "special importance": "強調",
  "special public celebration": "節慶",
  "spending plan": "預算",
  "spreading out": "分布",
  "standard for comparison": "基準",
  "standard for judgment": "標準",
  "start officially": "正式啟動",
  "state of balance": "平衡狀態",
  "state of failing financially": "破產狀態",
  "state the meaning of": "定義",
  "statement of dissatisfaction": "抱怨",
  "steady and not changing": "穩定的",
  "stock of goods": "庫存",
  "stop something planned": "取消",
  "storage building": "倉庫",
  "storage furniture": "櫃子",
  "store branch": "分店",
  "store seller": "零售商",
  "store selling medicine": "藥局",
  "straight and clear": "直接的",
  "strip for covering a wound": "繃帶",
  "substance for washing": "肥皂",
  "suggest": "建議",
  "suggest without saying directly": "暗示",
  "suggested meaning": "言外之意",
  "surrounding information": "脈絡",
  "sweet food after a meal": "甜點",
  "system of ideas": "理論體系",
  "system or process": "機制",
  "table of dates": "行事曆",
  "take and return later": "借用",
  "take money out": "提款",
  "tax on imports": "關稅",
  "tell apart": "區分",
  "timetable": "時間表",
  "to a higher floor": "往樓上",
  "together": "一起",
  "tool for cleaning teeth": "牙刷",
  "tool for measuring temperature": "溫度計",
  "tool for protection from rain": "雨傘",
  "toward the front": "向前",
  "trade one thing for another": "交換",
  "train waiting area": "月台",
  "training session": "研討會",
  "travel bag": "行李箱",
  "travel schedule": "行程表",
  "travel to work regularly": "通勤",
  "trip for pleasure": "出遊",
  "two-wheeled vehicle": "腳踏車",
  "unclear": "模糊的",
  "underground train system": "地鐵",
  "unfair preference": "偏見",
  "unfriendly": "敵意的",
  "untidy": "凌亂的",
  "use of a space": "使用率",
  "use outside services": "外包",
  "useful in real situations": "實用的",
  "useful source": "資源",
  "usefulness": "效用",
  "using computer technology": "數位的",
  "usual direction or habit": "傾向",
  "usually": "通常",
  "valuable property": "資產",
  "very important or analytical": "關鍵的或批判性的",
  "very small": "極少的",
  "very strong": "強烈的",
  "very tasty": "美味的",
  "waiting to be decided": "待定的",
  "walkway": "走道",
  "warm covering": "毯子",
  "warm knitted top": "毛衣",
  "wash quickly with water": "沖洗",
  "waste material": "垃圾",
  "watch over time": "監測",
  "watch regularly": "監控",
  "way of doing something": "方法",
  "weighing a lot": "沉重的",
  "welcome": "迎接",
  "well enough": "足夠好地",
  "well-based and acceptable": "有效的",
  "window covering": "窗簾",
  "wireless internet connection": "無線網路",
  "with attention": "仔細地",
  "with great attention": "密切地",
  "with little noise": "安靜地",
  "with one another": "一起",
  "within one country": "國內的",
  "within the area": "在本地",
  "within the company": "內部的",
  "without a clear pattern": "隨機的",
  "without danger": "安全地",
  "work out a number": "計算",
  "work out by numbers": "以數字計算",
  "work together": "合作",
  "working well without waste": "高效率的",
  "worldwide": "全球的",
  "wrapped object for delivery": "包裹",
  "written name approval": "簽名",
  "yearly": "年度的"
};
